### ISSUE TITLE
Problem with host_vars overriding 

### ISSUE THREAD

**Issue by Gomez** [plone/ansible-playbook#51]
I try to override a variable within a host_vars file:

inventory/host_vars/plone.yml
```
plone_target_path: /home/webmaster/buildouts/
```
Still the target stays as `/usr/local/plone-*`

I need to do it like this:

inventory/host_vars/plone.yml
```
instances: 
    - plone_target_path: /home/webmaster/buildouts/
```
playbooks/plone.yml
```
---
- name: Manage Plone
  hosts: [ 'plone_server' ]
  gather_facts: True
  become: True

  roles:

    - role: ansible.plone_server
      tags: ['role::plone_server']
      plone_config: "{{ instances[0] }}"
```
Now it works.
