### ISSUE TITLE
problem with centos7 provisioning - failure downloading/installing wv package

### ISSUE THREAD

**Issue by erkax** [plone/ansible-playbook#60]
Hello,
provisioning  with a**nsible (version 2.2.0 from fedora 25 repository)** and the **latest stable version of your playbook (version 1.2.10)** failed when running vagrant up **centos7**  with this local-configure.yml :

```
install_loadbalancer: yes
install_proxycache: yes
install_muninnode: no
install_mailserver: no
install_webserver: yes
install_logwatch: no
install_fail2ban: no
admin_email: "xxxxxx@xxxxxxx.be"
timezone: "Europe/Brussels\n"

playbook_plones:
    - plone_instance_name: xxxx4310
      plone_target_path: "/usr/local/plone"
      plone_use_supervisor: yes
      plone_initial_password: xxxxx
      plone_version: '4.3.10'
      plone_create_site: no
      plone_client_count: 4
      plone_zserver_threads: 2
      plone_zodb_cache_size: 50000
      plone_client_max_memory: 1000MB
      plone_backup_at:
         minute: 30
         hour: 1
         weekday: "*"
      plone_pack_at:
         minute: 30
         hour: 3
         weekday: 7
      plone_keep_days: 7
      plone_keep_backups: 3
      plone_autorun_buildout: no
      webserver_virtualhosts:
        - hostname: xxxxxxxxxx.be
          port: 80
          protocol: http
          extra: return 301 https://$server_name$request_uri;
        - hostname: xxxxxxxxxx.be
          port: 443
          default_server: yes
          zodb_path: /Plone
          protocol: https
          certificate_file: private/plone.crt
          key_file: private/plone.key 
```

There is a problem with the installation of wv from repoforge.org... This package is no longer online
```

TASK [plone.plone_server : CentOS 7: Ensure wv installed] **********************
fatal: [centos7]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://pkgs.repoforge.org/wv/wv-1.2.4-1.el6.rf.x86_64.rpm, 'NoneType' object has no attribute 'read'"}
```

Even the website hosting this repo no longer exist,  a better idea could be to use the package from epel for el6 https://dl.fedoraproject.org/pub/epel/6/x86_64/ it's probably more stable than repoforge.org but I don't know enough (yet) plone to test this

Best regards,
J.
